/* auto-generated by scripts/pack-extension.js — do not edit */
export const EXTENSION_VERSION = "1.3.6";
export const EXTENSION_ZIP_NAME = "safeserp-extension-1.3.6.zip";
export const EXTENSION_ZIP_URL = "/safeserp-extension-1.3.6.zip";
